name: Deploy New App Version (Frontend)

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: eu-west-1

      - name: Install dependecies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Create .env file
        run: |
          echo VITE_AWS_REGION=${{ secrets.VITE_AWS_REGION }} >> .env
          echo VITE_AWS_USER_POOL_ID=${{secrets.VITE_AWS_USER_POOL_ID }} >> .env
          echo VITE_AWS_USER_POOL_CLIENT_ID=${{ secrets.VITE_AWS_USER_POOL_CLIENT_ID }} >> .env
        working-directory: dist
          
      - name: Delete all objects in S3 bucket
        run: aws s3 rm s3://${{ secrets.BUCKET_NAME }} --recursive

      - name: Upload artifact to S3
        run: |
          aws s3 cp assets s3://${{ secrets.BUCKET_NAME }}/assets --recursive
          aws s3 cp index.html s3://${{ secrets.BUCKET_NAME }}/index.html
        working-directory: dist
